### ISSUE TITLE
Use of seqeval locally with Hugging face evaluate

### ISSUE THREAD

**Issue by BerndRusitschka** [chakki-works/seqeval#105]
I want to use the seqeval metric locally in my environment because I am blocked from internet access by my company when it comes to accessing resources on the internet.
I have already installed the Hugging Face evaluate package. I have access to the file "seqeval-1.2.2.tar.gz" but I have not yet installed it into my virtual environment.

When I call "evaluate.load("seqeval")" I get a ModuleNotFoundError.

My questions would be:

1.) What do I have to do in order to use seqeval locally in my virtual environment?
2.) Does anybody know what the use of this code snippet is?
https://huggingface.co/spaces/evaluate-metric/seqeval/blob/main/seqeval.py
It was used by a colleague of mine in order to compute seqeval metrics but I do not understand the logic.

Thanks in advance.

**Comment by jeffsgrover** [comment]
Using `evaluate.load()` instead of `datasets.load_metric()` solved the issue for me.
