### ISSUE TITLE
Weighted average versus macro average?

### ISSUE THREAD

**Issue by katiefraser** [chakki-works/seqeval#21]
I noticed that in computing the 'macro' average in the classification report, the result is weighted by the support for each class. My understanding of macro-averaging is that it treats each class equally (in contrast to micro-averaging, where large classes have a greater impact on the final result). e.g. see Manning (2009) p.280: "Macroaveraging
gives equal weight to each class" https://nlp.stanford.edu/IR-book/pdf/13bayes.pdf 

As a suggestion, to avoid confusion you could follow the sklearn model and have options for all three of micro-average, macro-average, and weighted average: https://scikit-learn.org/stable/modules/generated/sklearn.metrics.f1_score.html#sklearn.metrics.f1_score

**Comment by TheArowanaDude** [comment]
I just had this confusion myself. Would the 'macro' average computed on this program actually be the micro-average? Or would it be more accurate to call it simply a weighted average, and if that's the case, what is the exact difference between a weighted average vs a micro average?

**Comment by TheArowanaDude** [comment]
I also am confused by how the micro average is computed in this library. If someone could share insight on that, that would be really helpful!

**Comment by katiefraser** [comment]
@TheArowanaDude I don't think micro-average and weighted-average are necessarily the same thing (but haven't worked through the math), just noticed empirically that in the two datasets I'm working with they give extremely similar results, even in the case of unbalanced classes and poor performance in the smaller classes, where you would typically expect macro average to drop. 

Do you have a specific point of confusion about the micro-average implementation? It seems to me that they just take all the recognized entities across classes and compute P, R, and F on the pooled set of entities ..?

**Comment by TheArowanaDude** [comment]
I thought the way the micro-average is computed is by looking at the class size in proportion to the rest of the data and that would be its weight when evaluating the f1 score? That seems really similar to how the the weighted average(macro average in this program) is computed here. I don't see how the implementation of micro avg here evaluates the distribution of data.

Here's the reference I am going by
https://datascience.stackexchange.com/questions/45974/micro-f1-and-macro-f1-are-equal-in-binary-classification-and-i-dont-know-why

Thanks in advance!
