### ISSUE TITLE
string index out of range

### ISSUE THREAD

**Issue by captain2017** [chakki-works/seqeval#22]
![image](https://user-images.githubusercontent.com/27909557/62699572-6ea51100-ba12-11e9-8444-8f9cb7b500cf.png)
I don't know why string index out of range
['L', 'D', '1', '0', '_', '1', 'W', 'H', 'P', 'C', '下', '甲', '板', 'C', '1', '2', '井', '注', '水', '井', '采', '油', '树', '服', '务', '管', '汇', '处', '无', '堵', '头', '，', '注', '水', '压', '力', '高', '，', '存', '在', '安', '全', '隐', '患', '。'] ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-STATUS', 'I-STATUS', 'I-STATUS', 'O', 'B-STATUS', 'I-STATUS', 'I-STATUS', 'I-STATUS', 'I-STATUS', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']

**Comment by hellojet** [comment]
请问您解决了吗？我也出现了这个问题

**Comment by saharghannay** [comment]
Hi, how did you solve this problem please  ?

**Comment by smutuvi** [comment]
Facing similar error. Seam the maximum size of list allowed is 619. Values bigger than this triggers the error. It would be great to know how to solve it

**Comment by Hironsan** [comment]
Maybe you fed empty string into the `get_entities`:

```python
>>> get_entities([''])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/seqeval/seqeval/metrics/sequence_labeling.py", line 43, in get_entities
    tag = chunk[0]
IndexError: string index out of range
```

That is an invalid value. Please follow the supported format.
