### ISSUE TITLE
Not IOB2 evaluation schema

### ISSUE THREAD

**Issue by gui-li** [chakki-works/seqeval#23]
In [1]: y_true = [['B-Phone', "I-Phone"]]

In [2]: y_pred = [["I-Phone", "I-Phone"]]

In [3]: from seqeval.metrics import accuracy_score

In [4]: from seqeval.metrics import classification_report

In [5]: from seqeval.metrics import f1_score

In [6]: classification_report(y_true, y_pred)
Out[6]: '           precision    recall  f1-score   support\n\n    Phone       1.00      1.00      1.00         1\n\nmicro avg       1.00      1.00      1.00         1\nmacro avg       1.00      1.00      1.00         1\n'

This is what I tested. In iob2, the above data should be 0 precision and 0 recall.

**Comment by abhinavkashyap** [comment]
Has this been addressed in this repository ?? can seqeval be used for BIOUL tagging ?

**Comment by Hironsan** [comment]
seqeval deals with the schema automatically. In this case, it might be processed as IOB1.
OK. We need to be able to specify the schema explicitly:

```
from seqeval.schema import IOB2

classification_reoprt(y_true, y_pred, schema=IOB2)
```

**Comment by Hironsan** [comment]
New Interface:

https://github.com/chakki-works/seqeval/blob/enhancement/redesign/seqeval/scheme.py

**Comment by Hironsan** [comment]
As of v1.0.0:

```python
>>> from seqeval.metrics import classification_report
>>> from seqeval.scheme import IOB2
>>> y_true = [['B-Phone', "I-Phone"]]
>>> y_pred = [["I-Phone", "I-Phone"]]
>>> print(classification_report(y_true, y_pred, mode='strict', scheme=IOB2))
              precision    recall  f1-score   support

       Phone       0.00      0.00      0.00         1

   micro avg       0.00      0.00      0.00         1
   macro avg       0.00      0.00      0.00         1
weighted avg       0.00      0.00      0.00         1

```
