### ISSUE TITLE
Error during offline installation

### ISSUE THREAD

**Issue by jerilkuriakose** [chakki-works/seqeval#28]
In our company we can't use pip for online installation, we can only do offline installation. So `pip install seqeval[cpu]` doesnt work. So we downloaded the `seqeval v0.0.12` package from the releases. And tried installing using the following three commands:
```
python -m pip install --no-index --user --find-links="J:\USB\OPD\Repository\Python Pack\Latest Python Package\PythonPackage" "J:\USB\OPD\Repository\Python Pack\Latest Python Package\PythonPackage\seqeval-0.0.12.tar.gz"
```
and
```
python setup.py install
```
and
```
python -m pip install -e .
```
In all the cases we were getting the following error:
```
Looking in links: j:\USB\OPD\Repository\Python Pack\Latest Python Package\Python
Package
Processing j:\usb\opd\repository\python pack\latest python package\pythonpackage
\seqeval-0.0.12.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\Anaconda3\python.exe' -c 'import sys, setuptools,
tokenize; sys.argv[0] = '"'"'C:\\Users\\jk2446\\AppData\\Local\\Temp\\pip-req-bu
ild-5a2amt18\\setup.py'"'"'; __file__='"'"'C:\\Users\\jk2446\\AppData\\Local\\Te
mp\\pip-req-build-5a2amt18\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', op
en)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec
(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\jk2446\
AppData\Local\Temp\pip-req-build-5a2amt18\pip-egg-info'
         cwd: C:\Users\jk2446\AppData\Local\Temp\pip-req-build-5a2amt18\
    Complete output (27 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\jk2446\AppData\Local\Temp\pip-req-build-5a2amt18\setup.py",
 line 57, in <module>
        'Programming Language :: Python :: Implementation :: PyPy'
      File "C:\Users\jk2446\AppData\Roaming\Python\Python36\site-packages\setupt
ools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "C:\ProgramData\Anaconda3\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "C:\Users\jk2446\AppData\Roaming\Python\Python36\site-packages\setupt
ools\dist.py", line 448, in __init__
        k: v for k, v in attrs.items()
      File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 281, in __init
__
        self.finalize_options()
      File "C:\Users\jk2446\AppData\Roaming\Python\Python36\site-packages\setupt
ools\dist.py", line 740, in finalize_options
        ep.load()(self)
      File "C:\Users\jk2446\AppData\Roaming\Python\Python36\site-packages\setupt
ools\dist.py", line 747, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "C:\Users\jk2446\AppData\Roaming\Python\Python36\site-packages\setupt
ools_scm\integration.py", line 17, in version_keyword
        dist.metadata.version = get_version(**value)
      File "C:\Users\jk2446\AppData\Roaming\Python\Python36\site-packages\setupt
ools_scm\__init__.py", line 150, in get_version
        parsed_version = _do_parse(config)
      File "C:\Users\jk2446\AppData\Roaming\Python\Python36\site-packages\setupt
ools_scm\__init__.py", line 113, in _do_parse
        "use git+https://github.com/user/proj.git#egg=proj" % config.absolute_ro
ot
    LookupError: setuptools-scm was unable to detect version for 'C:\\Users\\jk2
446\\AppData\\Local\\Temp\\pip-req-build-5a2amt18'.

    Make sure you're either building from a fully intact git repository or PyPI
tarballs. Most other sources (such as GitHub's tarballs, a git checkout without
the .git folder) don't contain the necessary metadata and will not work.

    For example, if you're using pip, instead of https://github.com/user/proj/ar
chive/master.zip use git+https://github.com/user/proj.git#egg=proj
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check th
e logs for full command output.
```
Version details:
```
OS: Windows 7
Python: 3.6.3
Setuptools_scn: 3.3.3
Pip: 19.3.1
seqeval: 0.0.12
```
What might be the problem. Kindly help.

**Comment by MrKolen** [comment]
> In our company we can't use pip for online installation, we can only do offline installation. So `pip install seqeval[cpu]` doesnt work. So we downloaded the `seqeval v0.0.12` package from the releases. And tried installing using the following three commands:
> 
> ```
> python -m pip install --no-index --user --find-links="J:\USB\OPD\Repository\Python Pack\Latest Python Package\PythonPackage" "J:\USB\OPD\Repository\Python Pack\Latest Python Package\PythonPackage\seqeval-0.0.12.tar.gz"
> ```
> 
> and
> 
> ```
> python setup.py install
> ```
> 
> and
> 
> ```
> python -m pip install -e .
> ```
> 
> In all the cases we were getting the following error:
> 
> ```
> Looking in links: j:\USB\OPD\Repository\Python Pack\Latest Python Package\Python
> Package
> Processing j:\usb\opd\repository\python pack\latest python package\pythonpackage
> \seqeval-0.0.12.tar.gz
>     ERROR: Command errored out with exit status 1:
>      command: 'C:\ProgramData\Anaconda3\python.exe' -c 'import sys, setuptools,
> tokenize; sys.argv[0] = '"'"'C:\\Users\\jk2446\\AppData\\Local\\Temp\\pip-req-bu
> ild-5a2amt18\\setup.py'"'"'; __file__='"'"'C:\\Users\\jk2446\\AppData\\Local\\Te
> mp\\pip-req-build-5a2amt18\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', op
> en)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec
> (compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\jk2446\
> AppData\Local\Temp\pip-req-build-5a2amt18\pip-egg-info'
>          cwd: C:\Users\jk2446\AppData\Local\Temp\pip-req-build-5a2amt18\
>     Complete output (27 lines):
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "C:\Users\jk2446\AppData\Local\Temp\pip-req-build-5a2amt18\setup.py",
>  line 57, in <module>
>         'Programming Language :: Python :: Implementation :: PyPy'
>       File "C:\Users\jk2446\AppData\Roaming\Python\Python36\site-packages\setupt
> ools\__init__.py", line 145, in setup
>         return distutils.core.setup(**attrs)
>       File "C:\ProgramData\Anaconda3\lib\distutils\core.py", line 108, in setup
>         _setup_distribution = dist = klass(attrs)
>       File "C:\Users\jk2446\AppData\Roaming\Python\Python36\site-packages\setupt
> ools\dist.py", line 448, in __init__
>         k: v for k, v in attrs.items()
>       File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 281, in __init
> __
>         self.finalize_options()
>       File "C:\Users\jk2446\AppData\Roaming\Python\Python36\site-packages\setupt
> ools\dist.py", line 740, in finalize_options
>         ep.load()(self)
>       File "C:\Users\jk2446\AppData\Roaming\Python\Python36\site-packages\setupt
> ools\dist.py", line 747, in _finalize_setup_keywords
>         ep.load()(self, ep.name, value)
>       File "C:\Users\jk2446\AppData\Roaming\Python\Python36\site-packages\setupt
> ools_scm\integration.py", line 17, in version_keyword
>         dist.metadata.version = get_version(**value)
>       File "C:\Users\jk2446\AppData\Roaming\Python\Python36\site-packages\setupt
> ools_scm\__init__.py", line 150, in get_version
>         parsed_version = _do_parse(config)
>       File "C:\Users\jk2446\AppData\Roaming\Python\Python36\site-packages\setupt
> ools_scm\__init__.py", line 113, in _do_parse
>         "use git+https://github.com/user/proj.git#egg=proj" % config.absolute_ro
> ot
>     LookupError: setuptools-scm was unable to detect version for 'C:\\Users\\jk2
> 446\\AppData\\Local\\Temp\\pip-req-build-5a2amt18'.
> 
>     Make sure you're either building from a fully intact git repository or PyPI
> tarballs. Most other sources (such as GitHub's tarballs, a git checkout without
> the .git folder) don't contain the necessary metadata and will not work.
> 
>     For example, if you're using pip, instead of https://github.com/user/proj/ar
> chive/master.zip use git+https://github.com/user/proj.git#egg=proj
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check th
> e logs for full command output.
> ```
> 
> Version details:
> 
> ```
> OS: Windows 7
> Python: 3.6.3
> Setuptools_scn: 3.3.3
> Pip: 19.3.1
> seqeval: 0.0.12
> ```
> 
> What might be the problem. Kindly help.

Hello, I encountered the same problem as you when I tried to install through the source code. The process has been stopped at "Processing seqeval-0.0.12" and it seems that it will not continue to run. How do you solve it? Thank you!

**Comment by CheesedRoll** [comment]
Have same issue. Did anybody solve the problem?

**Comment by Singularsun** [comment]
`pip install setuptools_scm` first can sovle my problem.

**Comment by Hironsan** [comment]
Please install `setuptools_scm` ahead.
