### ISSUE TITLE
F_b score

### ISSUE THREAD

**Issue by rsuwaileh** [chakki-works/seqeval#35]
Hey, 

Is it possible to add F_beta to the list of measures? This is in case I want to weight P or R more than the other?
`F_b = (1 + b^2) * (precision * recall) / ((b^2 * precision) + recall)`
https://github.com/chakki-works/seqeval/blob/445d99798f6969f606dbf5978d936d5a8b33bbd1/seqeval/metrics/sequence_labeling.py#L124

`score = (1 + b**2) * p * r / ((b**2 * p) + r) if p + r > 0 else 0`
https://github.com/chakki-works/seqeval/blob/445d99798f6969f606dbf5978d936d5a8b33bbd1/seqeval/metrics/sequence_labeling.py#L149

**Comment by Hironsan** [comment]
As of v1.0.0, `precision_recall_fscore_support` function supports `beta`. You can calculate F-beta easily.

https://github.com/chakki-works/seqeval/blob/91215f5366b17136134f885ac4ac21a6093687bf/seqeval/metrics/v1.py#L100-L109
