### ISSUE TITLE
Plans for a Confusion matrix?

### ISSUE THREAD

**Issue by cgnarendiran** [chakki-works/seqeval#37]
Are there any plans to implement a confusion matrix computation for NER labels?
I see that the classification report already gives a lot of information required for evaluation. A confusion matrix would be a nice addition to present the prediction errors.

**Comment by Querela** [comment]
https://github.com/chakki-works/seqeval/blob/445d99798f6969f606dbf5978d936d5a8b33bbd1/seqeval/metrics/sequence_labeling.py#L255L285

`performance_measure`

should be this?

**Comment by Hironsan** [comment]
Please use `performance_measure` function.

**Comment by mustfkeskin** [comment]
performance_measure function returns only TP,FP,FN,TN
{'TP': 16617, 'FP': 199, 'FN': 38, 'TN': 1377}

I would like to see which entities  is are conflicted
