### ISSUE TITLE
Confusion matrix in addition to other metrics

### ISSUE THREAD

**Issue by al31415** [chakki-works/seqeval#48]
Hi,

While f1_score and other metrics are very informative, can confusion matrix be also added?
It is very useful to look on it in order to identify where exactly is mismatch in predictions.

**Comment by kaushikacharya** [comment]
I wonder how much confusion matrix at entity class level would be useful, given that there will be partial matches.

Personally, I have used [scikit-learn confusion matrix](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.confusion_matrix.html) at token level.

For named entity recognition, it creates something like this:
![image](https://user-images.githubusercontent.com/4562867/95686539-212ac200-0c1c-11eb-8474-6726488226a6.png)
