### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Saumajit** [chakki-works/seqeval#5]
Please provide a detailed step by step procedure for installing seqeval from your repo. I also tried to install from .whl file available in pypi.org

**_seqeval-0.0.6-py3-none-any.whl is not a supported wheel on this platform_** This is the error that it is showing. Please let me know how to use it. Thanks.

**Comment by icoxfog417** [comment]
Thank you for reporting the issue. Could you please let tell us about your platform?

* OS
* Python version
