### ISSUE TITLE
classification_report does not work on a single list/example

### ISSUE THREAD

**Issue by eloukas** [chakki-works/seqeval#58]
Hi, since the last update, the `classification_report` method works only with a list of lists and it does not support a single list.

How to reproduce the behaviour
---------
```
from seqeval.metrics import classification_report
from seqeval.scheme import IOB2

# Tutorial example
# OK, works
print('Example #1 (from tutorial) Works')
y_true = [['O', 'O', 'O', 'B-MISC', 'I-MISC', 'I-MISC', 'O'], ['B-PER', 'I-PER', 'O']]
y_pred = [['O', 'O', 'B-MISC', 'I-MISC', 'I-MISC', 'I-MISC', 'O'], ['B-PER', 'I-PER', 'O']]


print(classification_report(y_true, y_pred, output_dict=False, mode=None, scheme=IOB2))

# OK, works
print('Example #2 Works')
y_true2 = [['O', 'O', 'B-LOC']]
y_pred2 = [['O', 'B-LOC', 'O']]


print(classification_report(y_true2, y_pred2, output_dict=False, mode='strict', scheme=IOB2))

# NOT OK, DOES NOT WORK
print('Example #3 DOES NOT WORK')
y_true2 = ['O', 'O', 'B-LOC']
y_pred2 = ['O', 'B-LOC', 'O']
print(classification_report(y_true2, y_pred2, output_dict=False, mode='strict', scheme=IOB2))
```

Your Environment
---------

*   Operating System: Ubuntu 18.04.05 (LTS)
*   Python Version: 3.8
*   Package Version: 1.1.0

PS
--------
Probably the same will happen in precision, recall, f1 scores methods too. Haven't tested.

**Comment by kaushikacharya** [comment]
> `classification_report` method works only with a list of lists and it does not support a single list.

https://github.com/chakki-works/seqeval/blob/master/seqeval/metrics/sequence_labeling.py#L332
```
y_true : 2d array. Ground truth (correct) target values.
y_pred : 2d array. Estimated targets as returned by a classifier.
```
The arguments definition mentions that it has to be a **list of list**.

**Comment by Hironsan** [comment]
As @kaushikacharya said, you need to use a list of list:

```python
>>> y_true2 = [['O', 'O', 'B-LOC']]
>>> y_pred2 = [['O', 'B-LOC', 'O']]
>>> classification_report(y_true2, y_pred2, output_dict=False, mode='strict', scheme=IOB2)
              precision    recall  f1-score   support
         LOC       0.00      0.00      0.00         1
   micro avg       0.00      0.00      0.00         1
   macro avg       0.00      0.00      0.00         1
weighted avg       0.00      0.00      0.00         1
```

**Comment by eloukas** [comment]
Thank you for the quick response. This was not the case in the previous versions, so that's why I raised the issue.\
Also, I'd like to point out that sklearn's [classification_report](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.classification_report.html) can have a 1d array-like input, so maybe you could keep that in mind, if you agree, for future releases. Have a good day!
