### ISSUE TITLE
classification_report works uncorrectly

### ISSUE THREAD

**Issue by TQuy** [chakki-works/seqeval#6]
When running classification_report, I suppose the support column is the number of tags in y_true list. I have two lists `y_true.npy` and `y_pred.npy` , they are attached bellow
when I run classification_report it gives me support: 1379 for "LOC" tag, but the true number is 1377 tags

>           precision    recall  f1-score   support\n\n        
PER     0.4862    0.8423    0.6165      1294\n        
LOC     0.5914    0.3002    0.3983      1379\n        
ORG     0.2000    0.0474    0.0767       274\n       
MISC     0.4902    0.5102    0.5000        49\n\n

avg / total     0.5085    0.5147    0.4648      2996\n'

[y_true and y_pred.zip](https://github.com/chakki-works/seqeval/files/3105869/y_true.and.y_pred.zip)

**Comment by Hironsan** [comment]
The reason is there is some wrong annotation in your data:

```python
# In line 594
['O', 'O', 'O', 'O', 'O', 'O', 'B-LOC', 'I-LOC', 'I-LOC', 'I-LOC', 'O', 'B-LOC', 'I-LOC', 'O', 'I-LOC', 'O', 'I-LOC', 'O', 'B-LOC', 'I-LOC', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']
```

There are two isolates 'I-LOC's.

**Comment by TQuy** [comment]
thank you, I didn't expect the result of the contest is incorrect is incorrect

**Comment by TQuy** [comment]
Ah, I check, the sentence `594^th` tries to list 3 provinces (the word orders in Vietnamese is a little different, so I will translate it literally) 

> `Province`  `phước_sơn`   ` ,`   `nam_giang`   `,`   `đông_giang` 

> B-LOC  I-LOC O I-LOC O I-LOC (Where O is tag for comma)

So I think the annotation is not incorrect.

**Comment by TQuy** [comment]
Ah, I check, the sentence `594^th` tries to list 3 province names (the word orders in Vietnamese is a little different, so I will translate it literally) 

> `Province`  `phước_sơn`   ` ,`   `nam_giang`   `,`   `đông_giang` 

> B-LOC  I-LOC O I-LOC O I-LOC (Where O is tag for comma)

So I think the annotation is not incorrect, all of the tags above should make up to one `LOC` tag @Hironsan

**Comment by marma** [comment]
Two isolated I-LOCs is not invalid in the IOB format. In IOB2 it is though.

https://en.wikipedia.org/wiki/Inside%E2%80%93outside%E2%80%93beginning_(tagging)
