### ISSUE TITLE
F1-score issue

### ISSUE THREAD

**Issue by rajae-Bens** [chakki-works/seqeval#68]
Hi,

I am trying to execute the code in this google colab notebook 

https://colab.research.google.com/github/abhimishra91/transformers-tutorials/blob/master/transformers_ner.ipynb#scrollTo=9zwFzzBriLMO

but an error is generated when calculating the f1 score in the validation step

![Screen Shot 2020-10-28 at 9 12 02 AM](https://user-images.githubusercontent.com/58187895/97409330-b35de600-18fd-11eb-8429-4945155c5cd0.png)

could someone help plz
thank u

**Comment by Hironsan** [comment]
You should give a list of lists to `f1_score`:

```python
>>> from seqeval.metrics import f1_score
>>> y_true = [['O', 'O', 'O', 'B-MISC', 'I-MISC', 'I-MISC', 'O'], ['B-PER', 'I-PER', 'O']]
>>> y_pred = [['O', 'O', 'B-MISC', 'I-MISC', 'I-MISC', 'I-MISC', 'O'], ['B-PER', 'I-PER', 'O']]
>>> f1_score(y_true, y_pred)
0.50
```
