### ISSUE TITLE
Please remove tensorflow from setup.py

### ISSUE THREAD

**Issue by BrikerMan** [chakki-works/seqeval#7]
Since tensorflow is not directly required in this project, please remove it from the setup.py.
I have a gpu virtualenv, when I install seqeval it will install tensorflow-cpu to this environment, then I have to delete the tensorflow-cpu and re-install tensorflow-gpu.

**Comment by Hironsan** [comment]
Solved.

I added `extras_require` to setup.py.  We can install seqeval as follows:

```bash
# cpu environment
$ pip install seqeval[cpu]

# gpu environment
$ pip install seqeval[gpu]
```
