### ISSUE TITLE
Different f1 score in f1_score() and classification_report()

### ISSUE THREAD

**Issue by utsavg** [chakki-works/seqeval#9]
I am using above functions to compute f1 score for Named entity recognition where I am using 10 entities with BIO encoding.

f1_score() showing
0.437542201215395

where as Classification_report() showing
                                precision    recall  f1-score   support

             loc                0.11          0.75      0.19       102
       person               0.77          0.72      0.75        90
    company               0.85         0.74      0.79        70
    product                0.84          0.62      0.71        42
   facility                   0.72          0.81      0.76        26
      other                  0.76          0.65      0.70        83
musicartist               0.75          0.55      0.63        22
 sportsteam             0.91          0.67      0.77        15
      movie                1.00          0.57      0.73         7
     tvshow                1.00         0.50      0.67         6

avg / total                 0.65      0.70      0.61       463

**Comment by utsavg** [comment]
![F1 score](https://user-images.githubusercontent.com/15958833/56866394-35faa200-69f6-11e9-8d29-217e4feb45f4.JPG)

**Comment by Hironsan** [comment]
`f1_score` function calculates f1-micro, whereas `classification_report` function calculates f1-macro.

**Comment by deakkon** [comment]
Is this still true? Currenlty, the classification report prints out a different table:

     MISC       0.00      0.00      0.00         1
      PER       1.00      1.00      1.00         1

micro avg       0.33      0.50      0.40         2
macro avg       0.50      0.50      0.50         2

I assume the average param of f1_score doesnt do anythig atm?
