### ISSUE TITLE
No module named 'seqeval' even after installing the package

### ISSUE THREAD

**Issue by archanatikayatray19** [chakki-works/seqeval#94]
How to reproduce the problem
---------
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-40-584defff6e75> in <module>
----> 1 from seqeval.metrics import f1_score, accuracy_score

ModuleNotFoundError: No module named 'seqeval'

```bash
```

Your Environment
---------

*   Operating System: Windows 10 
*   Python Version:  Python 3.9.5
*   Package Version: 1.2.2

I am getting this error even after doing `!pip3 install seqeval`. Could someone please help with this?

**Comment by Hironsan** [comment]
I recommend you use a virtual environment(if you haven't used it yet). The following page may be helpful for you:

- [Installing packages using pip and virtual environments](https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/#installing-packages-using-pip-and-virtual-environments)

After activating the environment, please install `seqeval` and run the Python interpreter, and try import the package.

**Comment by datalee** [comment]
pip install setuptools_scm，then install seqeval
